### ISSUE TITLE
Unknown IP address version.

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/RakLib#13] opened 2017-11-26 17:02 UTC
```[16:45:02] [RakLibServer thread/CRITICAL]: UnexpectedValueException: "Unknown IP address version 255" (EXCEPTION) in "vendor/pmmp/raklib/protocol/Packet" at line 90
[16:45:02] [RakLibServer thread/DEBUG]: #0 vendor/pmmp/raklib/protocol/NewIncomingConnection(48): raklib\protocol\Packet->getAddress(string 0.0.0.0, integer 0, integer 255)
[16:45:02] [RakLibServer thread/DEBUG]: #1 vendor/pmmp/raklib/server/Session(460): raklib\protocol\NewIncomingConnection->decode()
[16:45:02] [RakLibServer thread/DEBUG]: #2 vendor/pmmp/raklib/server/Session(406): raklib\server\Session->handleEncapsulatedPacketRoute(raklib\protocol\EncapsulatedPacket object)
[16:45:02] [RakLibServer thread/DEBUG]: #3 vendor/pmmp/raklib/server/Session(540): raklib\server\Session->handleEncapsulatedPacket(raklib\protocol\EncapsulatedPacket object)
[16:45:02] [RakLibServer thread/DEBUG]: #4 vendor/pmmp/raklib/server/SessionManager(213): raklib\server\Session->handlePacket(raklib\protocol\DATA_PACKET_4 object)
[16:45:02] [RakLibServer thread/DEBUG]: #5 vendor/pmmp/raklib/server/SessionManager(138): raklib\server\SessionManager->receivePacket()
[16:45:02] [RakLibServer thread/DEBUG]: #6 vendor/pmmp/raklib/server/SessionManager(129): raklib\server\SessionManager->tickProcessor()
[16:45:02] [RakLibServer thread/DEBUG]: #7 vendor/pmmp/raklib/server/SessionManager(109): raklib\server\SessionManager->run()
[16:45:02] [RakLibServer thread/DEBUG]: #8 vendor/pmmp/raklib/server/RakLibServer(237): raklib\server\SessionManager->__construct(raklib\server\RakLibServer object, raklib\server\UDPServerSocket object)
[16:45:02] [RakLibServer thread/DEBUG]: #9 (): raklib\server\RakLibServer->run()
[16:45:02] [RakLibServer thread/NOTICE]: Blocked 77.87.102.132 for 5 seconds

**Comment by dktapps** [comment] 2017-11-26 17:03
Duplicate of #12

**Closed by dktapps** 2017-11-26 17:03 UTC
